logging the output data file full path so that logs can be traced to data file creation.  another package importing NEW_COMMANDS got ImportError: cannot import name 'NEW)COMMANDS' from partially initialized module 'telemetry_obd.add_commands' (most likely due to a circular import).  a little refactoring fixes this problem.