Exception: [kpa, lph, ratio] not defined in unit registry.  required some refactoring in order to use python-OBD library UnitRegistry object.   Also, kpa != kPa.  more refactoring to get all unit registry setup done in common functions.